In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import qgrid

In [5]:
data = pd.read_excel("order_products__prior.xlsx",index_col=0,sheetname=1)
data.head()

,1,10,23,25,27,28,34,45,54,79,...,49533,49567,49588,49605,49610,49618,49621,49628,49667,49683
ID,,,,,,,,,,,,,,,,,,,,,
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
frequent_itemsets = apriori(data, min_support=0.007, use_colnames=True)

In [12]:
type(frequent_itemsets)

pandas.core.frame.DataFrame

In [13]:
frequent_itemsets.head()

    support itemsets
0  0.010890     [45]
1  0.009609    [196]
2  0.007687    [260]
3  0.009609    [432]
4  0.008328    [890]

In [14]:
frequent_itemsets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 2 columns):
support     233 non-null float64
itemsets    233 non-null object
dtypes: float64(1), object(1)
memory usage: 3.7+ KB

In [15]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head()

  antecedants consequents   support  confidence      lift
0     (24852)     (27966)  0.161435    0.059524  1.474868
1     (27966)     (24852)  0.040359    0.238095  1.474868
2     (26209)     (47626)  0.039078    0.196721  4.206602
3     (47626)     (26209)  0.046765    0.164384  4.206602
4     (47626)     (22935)  0.046765    0.150685  3.856052

In [16]:
rules.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 5 columns):
antecedants    88 non-null object
consequents    88 non-null object
support        88 non-null float64
confidence     88 non-null float64
lift           88 non-null float64
dtypes: float64(3), object(2)
memory usage: 3.5+ KB

In [17]:
rules[rules["lift"]>1]

   antecedants consequents   support  confidence      lift
0      (24852)     (27966)  0.161435    0.059524  1.474868
1      (27966)     (24852)  0.040359    0.238095  1.474868
2      (26209)     (47626)  0.039078    0.196721  4.206602
3      (47626)     (26209)  0.046765    0.164384  4.206602
4      (47626)     (22935)  0.046765    0.150685  3.856052
5      (22935)     (47626)  0.039078    0.180328  3.856052
6      (47209)     (27966)  0.065343    0.127451  3.157952
7      (27966)     (47209)  0.040359    0.206349  3.157952
8      (24852)     (21903)  0.161435    0.123016  1.920278
9      (21903)     (24852)  0.064061    0.310000  1.920278
10     (13176)     (21903)  0.117873    0.070652  1.102880
11     (21903)     (13176)  0.064061    0.130000  1.102880
12     (47626)     (24852)  0.046765    0.246575  1.527397
13     (24852)     (47626)  0.161435    0.071429  1.527397
14     (47209)     (24964)  0.065343    0.117647  3.279412
15     (24964)     (47209)  0.035874    0.214286  3.279412
16     (26209)     (24852)  0.039078    0.278689  1.726321
17     (24852)     (26209)  0.161435    0.067460  1.726321
18     (25890)     (24852)  0.021781    0.470588  2.915033
19     (24852)     (25890)  0.161435    0.063492  2.915033
20     (26604)     (24852)  0.022422    0.342857  2.123810
21     (24852)     (26604)  0.161435    0.047619  2.123810
22     (13176)     (47209)  0.117873    0.168478  2.578378
23     (47209)     (13176)  0.065343    0.303922  2.578378
24     (24852)     (47766)  0.161435    0.103175  2.013194
25     (47766)     (24852)  0.051249    0.325000  2.013194
26     (13176)     (30391)  0.117873    0.070652  3.063557
27     (30391)     (13176)  0.023062    0.361111  3.063557
28     (13176)     (27966)  0.117873    0.119565  2.962560
29     (27966)     (13176)  0.040359    0.349206  2.962560
..         ...         ...       ...         ...       ...
58     (21137)     (27966)  0.082639    0.108527  2.689061
59     (27966)     (21137)  0.040359    0.222222  2.689061
60     (21137)     (47209)  0.082639    0.162791  2.491336
61     (47209)     (21137)  0.065343    0.205882  2.491336
62     (13176)     (42265)  0.117873    0.065217  2.483033
63     (42265)     (13176)  0.026265    0.292683  2.483033
64     (21137)     (47766)  0.082639    0.100775  1.966376
65     (47766)     (21137)  0.051249    0.162500  1.966376
66     (45007)     (21903)  0.026906    0.261905  4.088333
67     (21903)     (45007)  0.064061    0.110000  4.088333
68     (13176)     (30489)  0.117873    0.070652  2.564838
69     (30489)     (13176)  0.027546    0.302326  2.564838
70     (45066)     (24852)  0.032031    0.400000  2.477778
71     (24852)     (45066)  0.161435    0.079365  2.477778
72     (30489)     (24852)  0.027546    0.302326  1.872739
73     (24852)     (30489)  0.161435    0.051587  1.872739
74     (13176)     (22935)  0.117873    0.081522  2.086155
75     (22935)     (13176)  0.039078    0.245902  2.086155
76     (28204)     (24852)  0.030750    0.479167  2.968171
77     (24852)     (28204)  0.161435    0.091270  2.968171
78     (13176)     (21137)  0.117873    0.152174  1.841422
79     (21137)     (13176)  0.082639    0.217054  1.841422
80     (21137)     (24852)  0.082639    0.209302  1.296512
81     (24852)     (21137)  0.161435    0.107143  1.296512
82     (19057)     (24852)  0.025625    0.275000  1.703472
83     (24852)     (19057)  0.161435    0.043651  1.703472
84     (49683)     (24852)  0.027546    0.372093  2.304910
85     (24852)     (49683)  0.161435    0.063492  2.304910
86     (24852)      (8277)  0.161435    0.043651  1.892747
87      (8277)     (24852)  0.023062    0.305556  1.892747

[88 rows x 5 columns]

In [18]:
qgrid.show_grid(rules)

In [19]:
rules.to_excel("Gariz_lift.xlsx")